### ISSUE TITLE
vm_is_running method always returns False

### ISSUE THREAD

**Issue by Sherlock-IT** [marmig0404/pymemuc#13]
I'm using the vm_is_running method from the memuc module to check whether a virtual machine is running or not, but it always returns False, even when the virtual machine is running.
```
import memuc

vm_index = 1 # Replace with the index of your virtual machine
print(memuc.vm_is_running(vm_index)) # Always prints False
```

**Comment by marmig0404** [comment]
I suspect this is something to do with starting the VM as a different user than the one checking it, such as starting the VM from MEmu's GUI as admin, and checking with your script as normal user.

`memuc.exe`, the underlying component of PyMemuc, only detects VMs running from the same user.

Try using the same script to start, and then check if the VM is running:
```python
from pymemuc import PyMemuc

memuc = PyMemuc(debug=True)
vm_index = 1

memuc.start_vm(vm_index=vm_index)
print(memuc.vm_is_running(vm_index))
```
