### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by photkey** [marmig0404/pymemuc#20]
![Snipaste_2023-04-11_00-24-18](https://user-images.githubusercontent.com/60434581/230945567-51f74c0f-4427-4966-9e57-ea38c8866d88.png)

I'm using python 3.9 and this project requires at least python 3.10. Is this version too high, should I consider adapting to a lower version of python?

**Comment by marmig0404** [comment]
Ah this error is caused by alternative syntax for type annotations for Unions only supported by >=3.10. I can fix this to support 3.9 without losing type hinting functionality.

Fix will be out soon

**Comment by marmig0404** [comment]
Updated version out: https://pypi.org/proect/pymemuc/0.2.4/
Thanks for raising the issue! 😊
